apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: eu.gcr.io/ticketing-dev-296116/payments
          env: 
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID # unique 
              valueFrom: # unique solution
                fieldRef:
                  fieldPath: metadata.name # match the id of the client to an actual running copy of our ticket services , name of the pod as a solution
            - name: MONGO_URI
              value: 'mongodb://payments-mongo-srv:27017/payments' # hardcoded URI
            - name: JWT_KEY #INSIDE OF payments APP
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
                  #If you load in scaffold some uncofig secret key kube wont load the pod
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
